### PR TITLE
Support async config initialization via promises

### LINKED ISSUE #131: Dynamic list of servers
Hi,

In my company we use AWS and deploy on multiple servers (dynamic, on-demmand). Since it is a scalable platform, we don't know the list of servers by default and we can't hardcode them on the `shipitfile.js`.

It would be nice if we can apply the `shipitConfig` through a callback or similar; then we can get the list of servers and pass it to `shipitConfig` synchronously to deploy as needed.

Please, any suggestion how can we do this? Thanks in advance.

### PR DESCRIPTION
**Pull request by rfunduk**
Motivated by and fixes #131, see there for discussion.

### CODE REVIEW

**Comment by rfunduk** [comment]
It seems the checks are failing because node only got `Promise` via v8 as of 0.12.

**Comment by alexfernandez** [comment]
@rfunduk You can use `global.Promise`:

    if (global.Promise && pendingConfig instanceof global.Promise) {

So that tests work in v0.10.

**Comment by xgalen** [comment]
rfunduk v0.10 won't be maintained the next october. Maybe you can update the `.travis.yml`, remove 0.10 and add v4.

**Comment by rfunduk** [comment]
I recently switched the project I'm working on to use Bluebird instead of the native Promises. This, frustratingly, broke the code in this PR since it checks `pendingConfig instanceof Promise`. So after a bit of reading it became obvious that checking like that is not best, and instead I should simply wrap whatever `pendingConfig` is in `Promise.resolve` and treat it as a promise no matter what (see [here](http://stackoverflow.com/questions/27746304/how-do-i-tell-if-an-object-is-a-promise) for example... wrapping a promise with `Promise.resolve` does nothing).

So, if that sounds fine to you I'll make that change to this PR shortly.

**Comment by alexfernandez** [comment]
Sounds fine. Let us hope the maintainers notice this PR and merge it once it is ready! @neoziro is this project still maintained? Not much activity lately.

**Comment by timkelty** [comment]
Hey guys - sorry for the delay, and for the inactivity on the project lately.

Good work on this one - merging it in.
Will release to NPM later tonight.

Thanks again!

**Pull request merged**
