### PR TITLE
Adding localCopy to copy from remote to local.

### PR DESCRIPTION
**Pull request by timkelty**
Adding method to copy from remote to local.

Depends on https://github.com/neoziro/ssh-pool/pull/3

### CODE REVIEW

**Comment by timkelty** [comment]
I matched up options with https://github.com/neoziro/ssh-pool/issues/2.

**Comment by neoziro** [comment]
@timkelty we will just update the remoteCopy method that will support the same options as ssh-pool, I will do it later. If you want to be in contributor, then update this PR and I will merge it.

**Comment by timkelty** [comment]
Ok, now passing a full options hash, removed `localCopy`.

**Comment by neoziro** [comment]
@timkelty options should be optional, else it's a breaking change in the API

**Comment by timkelty** [comment]
My bad, I'll fix it.

**Comment by timkelty** [comment]
Ok, they're optional now :)

**Pull request merged**
