### PR TITLE
V4.0.0

### PR DESCRIPTION
**Pull request by neoziro**
PR relative to https://github.com/shipitjs/shipit/issues/156

### CODE REVIEW

**Comment by timkelty** [comment]
Great. Will start reviewing this today!

**Comment by neoziro** [comment]
@timkelty thanks, it's almost finish for ssh-pool and shipit-cli 🌟. I would like to add some integration tests. Any idea to achieve it?

**Comment by neoziro** [comment]
@timkelty I added integration tests on test.shipitjs.com, a remote server. It is safer for us.

**Comment by neoziro** [comment]
@timkelty the v4 is nearly finished. Last step is documentation.

**Pull request merged**
