### PR TITLE
Add keepWorkspace option

### PR DESCRIPTION
**Pull request by SleepWalker**
This is a last portion of improvements to finally solve #207

I've added new config option, which will disable `workspace` deletion step and also documented two possible ways of configuring `workspace` path

### CODE REVIEW

**Comment by SleepWalker** [comment]
@neoziro can you please take a look?

**Comment by neoziro** [comment]
Hello @SleepWalker, it looks good but could you please try to make tests pass?

**Comment by SleepWalker** [comment]
oh my, haven't noticed that :) It's now should be green (I hope)

**Comment by SleepWalker** [comment]
@neoziro there is an issue because both shallowClone and workspace props set deploy config:

image

According to the logic before my PR, that `workspace` from config will be silently overridden with tmp dir, if  `shallowClone: true`. I've removed that logic in my PR and if `workspace` config is set, than it has the biggest priority.

I'll revert this change and will log the warning, that workspace from config was overridden with tmp dir because of shallowClone option. This will be more clear to use and won't be a breaking change for existing users (and won't break tests too)

**Comment by neoziro** [comment]
Thanks!

**Pull request merged**
