### PR TITLE
Fix doc wrt require and import use

### PR DESCRIPTION
**Pull request by madarche**
after the 4 release

### CODE REVIEW

**Comment by neoziro** [comment]
Thanks for this, but the correct fix is to fix the export in `shipit-deploy`.

Use `module.exports` instead of `export default` in this file https://github.com/shipitjs/shipit/blob/master/packages/shipit-deploy/src/index.js#L5

**Comment by madarche** [comment]
Thanks for your fast answer @neoziro.

It depends on your intentions and the design you want. So I let you close this issue depending on what you decide.

**Comment by neoziro** [comment]
Closed in favor of #181

**Comment by madarche** [comment]
Thanks @neoziro

**Pull request closed without merging**
